### ISSUE TITLE
Wound healing error at ExportToSpreadsheet

### ISSUE THREAD

**Issue by minh-doan** [CellProfiler/examples#23]
- Bad in CP3: Error at ExportToSpreatsheet >> give .csv no values (only headers). If run headless, ends with error.
- Good in CP2.2: all is fine

Error message: "The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()"

<img width="1013" alt="wound healing - error - cp3 headless" src="https://user-images.githubusercontent.com/22305129/29727542-568362f4-89a2-11e7-811a-f8609fe8ce46.png">

**Comment by bethac07** [comment]
Can you post the text of the error, not a picture of it please?

**Comment by minh-doan** [comment]
```
Exception in thread "Thread-1" java.io.EOFException: Attempting to read beyond end of file.
	at loci.common.NIOFileHandle.readFloat(NIOFileHandle.java:350)
	at loci.common.RandomAccessInputStream.readFloat(RandomAccessInputStream.java:501)
	at loci.formats.in.PQBinReader.isThisType(PQBinReader.java:96)
Caused by: java.nio.BufferUnderflowException
	at java.nio.Buffer.nextGetIndex(Buffer.java:506)
	at java.nio.HeapByteBuffer.getFloat(HeapByteBuffer.java:463)
	at loci.common.NIOFileHandle.readFloat(NIOFileHandle.java:348)
	... 2 more
Caught exception in class loci.formats.in.PQBinReader.isThisType
Exception in thread "Thread-1" java.lang.IllegalArgumentException
	at java.nio.Buffer.position(Buffer.java:244)
	at loci.common.NIOFileHandle.buffer(NIOFileHandle.java:603)
	at loci.common.NIOFileHandle.seek(NIOFileHandle.java:291)
	at loci.common.RandomAccessInputStream.seek(RandomAccessInputStream.java:174)
	at loci.formats.tiff.TiffParser.<init>(TiffParser.java:113)
	at loci.formats.in.FlowSightReader.isThisType(FlowSightReader.java:101)
Caught exception in class loci.formats.in.FlowSightReader.isThisType
Fri Aug 25 14:50:36 2017: Image # 1, module NamesAndTypes # 3: 1.14 sec
Fri Aug 25 14:50:37 2017: Image # 1, module Groups # 4: 0.00 sec
Fri Aug 25 14:50:37 2017: Image # 1, module ColorToGray # 5: 0.09 sec
Fri Aug 25 14:50:37 2017: Image # 1, module Smooth # 6: 0.61 sec
Fri Aug 25 14:50:38 2017: Image # 1, module IdentifyPrimaryObjects # 7: 2.24 sec
Fri Aug 25 14:50:40 2017: Image # 1, module MeasureImageAreaOccupied # 8: 0.07 sec
Fri Aug 25 14:50:40 2017: Image # 1, module ExportToSpreadsheet # 9: 0.00 sec
Fri Aug 25 14:50:40 2017: Image # 2, module Images # 1: 0.00 sec
Fri Aug 25 14:50:40 2017: Image # 2, module Metadata # 2: 0.00 sec
Exception in thread "AWT-AppKit" java.io.EOFException: Attempting to read beyond end of file.
	at loci.common.NIOFileHandle.readFloat(NIOFileHandle.java:350)
	at loci.common.RandomAccessInputStream.readFloat(RandomAccessInputStream.java:501)
	at loci.formats.in.PQBinReader.isThisType(PQBinReader.java:96)
Caused by: java.nio.BufferUnderflowException
	at java.nio.Buffer.nextGetIndex(Buffer.java:506)
	at java.nio.HeapByteBuffer.getFloat(HeapByteBuffer.java:463)
	at loci.common.NIOFileHandle.readFloat(NIOFileHandle.java:348)
	... 2 more
Caught exception in class loci.formats.in.PQBinReader.isThisType
Exception in thread "AWT-AppKit" java.lang.IllegalArgumentException
	at java.nio.Buffer.position(Buffer.java:244)
	at loci.common.NIOFileHandle.buffer(NIOFileHandle.java:603)
	at loci.common.NIOFileHandle.seek(NIOFileHandle.java:291)
	at loci.common.RandomAccessInputStream.seek(RandomAccessInputStream.java:174)
	at loci.formats.tiff.TiffParser.<init>(TiffParser.java:113)
	at loci.formats.in.FlowSightReader.isThisType(FlowSightReader.java:101)
Caught exception in class loci.formats.in.FlowSightReader.isThisType
Fri Aug 25 14:50:40 2017: Image # 2, module NamesAndTypes # 3: 0.61 sec
Fri Aug 25 14:50:40 2017: Image # 2, module Groups # 4: 0.00 sec
Fri Aug 25 14:50:40 2017: Image # 2, module ColorToGray # 5: 0.09 sec
Fri Aug 25 14:50:40 2017: Image # 2, module Smooth # 6: 0.59 sec
Fri Aug 25 14:50:41 2017: Image # 2, module IdentifyPrimaryObjects # 7: 2.30 sec
Fri Aug 25 14:50:43 2017: Image # 2, module MeasureImageAreaOccupied # 8: 0.17 sec
Fri Aug 25 14:50:43 2017: Image # 2, module ExportToSpreadsheet # 9: 0.00 sec
Failed to complete post_run processing for module ExportToSpreadsheet.
Traceback (most recent call last):
  File "/Users/minhdoan/CellProfiler/cellprofiler/pipeline.py", line 2167, in post_run
    module.post_run(workspace)
  File "/Users/minhdoan/CellProfiler/cellprofiler/modules/exporttospreadsheet.py", line 587, in post_run
    self.run_objects(object_names, workspace, first_group)
  File "/Users/minhdoan/CellProfiler/cellprofiler/modules/exporttospreadsheet.py", line 642, in run_objects
    workspace, settings_group)
  File "/Users/minhdoan/CellProfiler/cellprofiler/modules/exporttospreadsheet.py", line 878, in make_image_file
    elif np.isnan(value):
ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()
```

**Comment by bethac07** [comment]
I updated your text to put it in code blocks (the '<>' thing in the menu, or you can put three ` marks both before and after the text)

**Comment by bethac07** [comment]
https://github.com/CellProfiler/CellProfiler/issues/3318

**Comment by bethac07** [comment]
Closed via https://github.com/CellProfiler/CellProfiler/pull/3324
