### ISSUE TITLE
Colocalization error at CalculateMath

### ISSUE THREAD

**Issue by minh-doan** [CellProfiler/examples#24]
- Bad in CP3: error at CalculateMath
- Good in CP2.2: all is fine

Error messages:
ValueError: operands could not be broadcast together with shapes (1159,) (1573,)

ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

**Comment by minh-doan** [comment]
```
Fri Aug 25 14:52:50 2017: Image # 1, module CorrectIlluminationCalculate # 5: 0.48 sec
Fri Aug 25 14:52:50 2017: Image # 1, module CorrectIlluminationCalculate # 6: 0.41 sec
Fri Aug 25 14:52:51 2017: Image # 1, module CorrectIlluminationApply # 7: 0.00 sec
Fri Aug 25 14:52:51 2017: Image # 1, module Align # 8: 2.72 sec
Fri Aug 25 14:52:53 2017: Image # 1, module MeasureCorrelation # 9: 2.66 sec
Fri Aug 25 14:52:56 2017: Image # 1, module IdentifyPrimaryObjects # 10: 1.10 sec
Fri Aug 25 14:52:57 2017: Image # 1, module IdentifyPrimaryObjects # 11: 1.14 sec
Fri Aug 25 14:52:58 2017: Image # 1, module RelateObjects # 12: 0.26 sec
Fri Aug 25 14:52:59 2017: Image # 1, module ExpandOrShrinkObjects # 13: 0.17 sec
Fri Aug 25 14:52:59 2017: Image # 1, module ExpandOrShrinkObjects # 14: 0.17 sec
Fri Aug 25 14:52:59 2017: Image # 1, module ExpandOrShrinkObjects # 15: 0.24 sec
Fri Aug 25 14:52:59 2017: Image # 1, module ExpandOrShrinkObjects # 16: 0.25 sec
Fri Aug 25 14:52:59 2017: Image # 1, module RelateObjects # 17: 0.10 sec
Fri Aug 25 14:53:00 2017: Image # 1, module ClassifyObjects # 18: 0.01 sec
Fri Aug 25 14:53:00 2017: Image # 1, module FilterObjects # 19: 0.22 sec
Fri Aug 25 14:53:00 2017: Image # 1, module MaskObjects # 20: 0.12 sec
Fri Aug 25 14:53:00 2017: Image # 1, module MeasureImageAreaOccupied # 21: 0.23 sec
Error detected during run of module CalculateMath
Traceback (most recent call last):
  File "/Users/minhdoan/CellProfiler/cellprofiler/pipeline.py", line 1763, in run_with_yield
    self.run_module(module, workspace)
  File "/Users/minhdoan/CellProfiler/cellprofiler/pipeline.py", line 2007, in run_module
    module.run(workspace)
  File "/Users/minhdoan/CellProfiler/cellprofiler/modules/calculatemath.py", line 401, in run
    else None)
  File "/Users/minhdoan/CellProfiler/cellprofiler/modules/calculatemath.py", line 440, in compute_operation
    result = numerator / denominator
ValueError: operands could not be broadcast together with shapes (1189,) (1624,) 
Fri Aug 25 14:53:00 2017: Image # 1, module CalculateMath # 22: 0.00 sec
```

**Comment by bethac07** [comment]
https://github.com/CellProfiler/CellProfiler/issues/3318

**Comment by bethac07** [comment]
Closed via https://github.com/CellProfiler/CellProfiler/pull/3324
