### ISSUE TITLE
ExampleIlluminationCorrection_Example1_AllMethod error as SaveImages

### ISSUE THREAD

**Issue by minh-doan** [CellProfiler/examples#25]
- Bad in CP3: Error at SaveImages TIFF 64-bit
- Good in CP2.2: Save TIFF .mat just fine.
Error message:

ValueError: Images of type float must be between -1 and 1

**Comment by minh-doan** [comment]
```
Caught exception in class loci.formats.in.PQBinReader.isThisType
Exception in thread "Thread-1" java.lang.IllegalArgumentException
	at java.nio.Buffer.position(Buffer.java:244)
	at loci.common.NIOFileHandle.buffer(NIOFileHandle.java:603)
	at loci.common.NIOFileHandle.seek(NIOFileHandle.java:291)
	at loci.common.RandomAccessInputStream.seek(RandomAccessInputStream.java:174)
	at loci.formats.tiff.TiffParser.<init>(TiffParser.java:113)
	at loci.formats.in.FlowSightReader.isThisType(FlowSightReader.java:101)
Caught exception in class loci.formats.in.FlowSightReader.isThisType
Fri Aug 25 14:54:08 2017: Image # 1, module Images # 1: 0.00 sec
Fri Aug 25 14:54:08 2017: Image # 1, module Metadata # 2: 0.00 sec
Exception in thread "Thread-1" java.io.EOFException: Attempting to read beyond end of file.
	at loci.common.NIOFileHandle.readFloat(NIOFileHandle.java:350)
	at loci.common.RandomAccessInputStream.readFloat(RandomAccessInputStream.java:501)
	at loci.formats.in.PQBinReader.isThisType(PQBinReader.java:96)
Caused by: java.nio.BufferUnderflowException
	at java.nio.Buffer.nextGetIndex(Buffer.java:506)
	at java.nio.HeapByteBuffer.getFloat(HeapByteBuffer.java:463)
	at loci.common.NIOFileHandle.readFloat(NIOFileHandle.java:348)
	... 2 more
Caught exception in class loci.formats.in.PQBinReader.isThisType
Exception in thread "Thread-1" java.lang.IllegalArgumentException
	at java.nio.Buffer.position(Buffer.java:244)
	at loci.common.NIOFileHandle.buffer(NIOFileHandle.java:603)
	at loci.common.NIOFileHandle.seek(NIOFileHandle.java:291)
	at loci.common.RandomAccessInputStream.seek(RandomAccessInputStream.java:174)
	at loci.formats.tiff.TiffParser.<init>(TiffParser.java:113)
	at loci.formats.in.FlowSightReader.isThisType(FlowSightReader.java:101)
Caught exception in class loci.formats.in.FlowSightReader.isThisType
Fri Aug 25 14:54:08 2017: Image # 1, module NamesAndTypes # 3: 0.08 sec
Fri Aug 25 14:54:08 2017: Image # 1, module Groups # 4: 0.00 sec
/usr/local/lib/python2.7/site-packages/skimage/util/dtype.py:122: UserWarning: Possible precision loss when converting from float32 to uint8
  .format(dtypeobj_in, dtypeobj_out))
Fri Aug 25 14:54:08 2017: Image # 1, module CorrectIlluminationCalculate # 5: 0.19 sec
Fri Aug 25 14:54:09 2017: Image # 1, module CorrectIlluminationApply # 6: 0.00 sec
Fri Aug 25 14:54:09 2017: Image # 1, module CorrectIlluminationCalculate # 7: 0.55 sec
Fri Aug 25 14:54:09 2017: Image # 1, module CorrectIlluminationApply # 8: 0.00 sec
Error detected during run of module SaveImages
Traceback (most recent call last):
  File "/Users/minhdoan/CellProfiler/cellprofiler/pipeline.py", line 1763, in run_with_yield
    self.run_module(module, workspace)
  File "/Users/minhdoan/CellProfiler/cellprofiler/pipeline.py", line 2007, in run_module
    module.run(workspace)
  File "/Users/minhdoan/CellProfiler/cellprofiler/modules/saveimages.py", line 440, in run
    should_save = self.run_image(workspace)
  File "/Users/minhdoan/CellProfiler/cellprofiler/modules/saveimages.py", line 481, in run_image
    self.save_image(workspace)
  File "/Users/minhdoan/CellProfiler/cellprofiler/modules/saveimages.py", line 570, in save_image
    pixels = skimage.util.img_as_float(pixels)
  File "/usr/local/lib/python2.7/site-packages/skimage/util/dtype.py", line 336, in img_as_float
    return convert(image, np.float64, force_copy)
  File "/usr/local/lib/python2.7/site-packages/skimage/util/dtype.py", line 236, in convert
    raise ValueError("Images of type float must be between -1 and 1.")
ValueError: Images of type float must be between -1 and 1.
Fri Aug 25 14:54:09 2017: Image # 1, module SaveImages # 9: 0.00 sec
```

**Comment by bethac07** [comment]
See [CellProfiler issue 2822](https://github.com/CellProfiler/CellProfiler/issues/2822) .  We can fix this once we fix that.

**Comment by minh-doan** [comment]
Fixed SaveImages , using .npy instead of TIFF 64-bit
